### ISSUE TITLE
缺少很多依赖，编译打包不成功

### ISSUE THREAD

**Issue by qiyaocloud** [Meedu/backend#16]
### 缺少很多依赖，编译打包不成功
![WX20200703-160831](https://user-images.githubusercontent.com/66176454/86447271-ae21cd80-bd47-11ea-8cea-6d0884a43515.png)
根据提示安装了依赖后，编译打包还是出错
![WX20200703-160500](https://user-images.githubusercontent.com/66176454/86447347-cd205f80-bd47-11ea-876c-64c33d516e28.png)

系统：Macos 15.5
node: v14.4.0
yarn: 1.22.4

**Comment by qiyaocloud** [comment]
建议作者把您能运行的dist放到项目中去，能保证项目能正常运行

**Comment by Qsnh** [comment]
使用最新版的node打包
